### ISSUE TITLE
pck文件不存在

### ISSUE THREAD

**Issue by danliangsky** [AI-Hobbyist/StarRail_Datasets#2]
游戏路径StarRail\Game\StarRail_Data\StreamingAssets\Audio\AudioPackage\Windows\DecodedBanks\Chinese(PRC)
下为啥什么文件都没有呢

**Comment by danliangsky** [comment]
![image](https://github.com/AI-Hobbyist/StarRail_Datasets/assets/128498547/791d3481-9c40-4a78-92ec-6aa55f51c118)
这是人物的pck吧 用wwise-unpacker解码后没有生成wav文件

**Comment by Erythrocyte3803** [comment]
应该在这里 X:\Program Files\Star Rail\Game\StarRail_Data\Persistent\Audio\AudioPackage\Windows\Chinese(PRC) X代表你的盘符

**Comment by danliangsky** [comment]
> 应该在这里 X:\Program Files\Star Rail\Game\StarRail_Data\Persistent\Audio\AudioPackage\Windows\Chinese(PRC) X代表你的盘符
